# -*- coding: utf-8 -*-
"""dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16pEWcabNGHbelTRWHvmQ_6QhMqmi6vjb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

# Set Page Config
st.set_page_config(page_title="Olist E-Commerce Dashboard", layout="wide")

# Load Data
@st.cache_data
def load_data():
    df = pd.read_csv("olist_final_dataset.csv")
    df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
    return df

all_df = load_data()

# Header
st.title("📊 Brazilian E-Commerce Dashboard")
st.markdown("Dashboard ini menganalisis performa penjualan dan kepuasan pelanggan pada periode 2017-2018.")

# Sidebar (Filter Waktu)
min_date = all_df["order_purchase_timestamp"].min()
max_date = all_df["order_purchase_timestamp"].max()

with st.sidebar:
    st.image("https://github.com/dicodingacademy/assets/raw/main/logo.png")
    start_date, end_date = st.date_input(
        label='Rentang Waktu',
        min_value=min_date,
        max_value=max_date,
        value=[min_date, max_date]
    )

# Filter data berdasarkan sidebar
main_df = all_df[(all_df["order_purchase_timestamp"] >= str(start_date)) &
                (all_df["order_purchase_timestamp"] <= str(end_date))]

# --- PERTANYAAN 1: PRODUK TERLARIS ---
st.subheader("Produk dengan Performa Terbaik")
col1, col2 = st.columns(2)

with col1:
    # Revenue tertinggi
    top_revenue = main_df.groupby("product_category_name_english").price.sum().sort_values(ascending=False).head(5)
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(x=top_revenue.values, y=top_revenue.index, palette="viridis", ax=ax)
    ax.set_title("Top 5 Kategori Berdasarkan Revenue")
    st.pyplot(fig)

with col2:
    # Volume tertinggi
    top_volume = main_df.groupby("product_category_name_english").order_id.nunique().sort_values(ascending=False).head(5)
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.barplot(x=top_volume.values, y=top_volume.index, palette="magma", ax=ax)
    ax.set_title("Top 5 Kategori Berdasarkan Volume Pesanan")
    st.pyplot(fig)

# --- PERTANYAAN 2: KEPUASAN & LOGISTIK ---
st.subheader("Kepuasan Pelanggan & Efisiensi Pengiriman")
# Hitung korelasi sederhana di dashboard
fig, ax = plt.subplots(figsize=(12, 6))
sns.regplot(x="delivery_time", y="review_score", data=main_df.sample(min(1000, len(main_df))), scatter_kws={'alpha':0.3})
ax.set_title("Korelasi Lama Pengiriman vs Skor Review")
st.pyplot(fig)

st.caption("Copyright (c) Ulum Hikam 2026")